#!/bin/sh
./monerod \
		--testnet \
		--no-igd \
		--hide-my-port \
		--data-dir .localnet/xmr_local/node1 \
		--p2p-bind-ip 127.0.0.1 \
		--p2p-bind-port 48080 \
		--rpc-bind-port 48081 \
		--no-zmq \
		--add-exclusive-node 127.0.0.1:28080 \
		--rpc-access-control-origins http://localhost:8080 \
		--fixed-difficulty 400