#!/bin/sh
IP=127.0.0.1
PORT=18082
METHOD="open_wallet"
PARAMS="{\"filename\":\"emptywallet\"}"
curl \
    -u username:password --digest \
    http://$IP:$PORT/json_rpc \
    -d '{"jsonrpc":"2.0","id":"0","method":"'$METHOD'","params":'"$PARAMS"'}' \
    -H 'Content-Type: application/json'
