#!/bin/sh
IP=127.0.0.1
PORT=18082
curl \
    -u username:password --digest \
    http://$IP:$PORT/json_rpc \
    -d '{"jsonrpc":"2.0","id":"0","method":"stop_wallet"}' \
    -H 'Content-Type: application/json'